version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: frontend/its-tasty
    schedule:
      interval: daily
