version: '3.3'
services:
  its-tasty:
    image: "its-tasty:latest"
    environment:
      - OIDC_SECRET
      - OIDC_CALLBACK_URL
      - OIDC_PROVIDER_URL
      - OIDC_ID
    container_name: its-tasty
    ports:
      - "8080:80"