version: '3.3'
services:
  its-tasty-backend:
    image: "its-tasty:latest"
    container_name: its-tasty-backend
    environment:
      - OIDC_SECRET
      - OIDC_CALLBACK_URL
      - OIDC_PROVIDER_URL
      - OIDC_ID
      - BOT_API_TOKEN
      - DB_URL
      - DB_NAME
      - DB_USER
      - DB_PW
      - URL_AFTER_LOGIN
      - URL_AFTER_LOGOUT
    ports:
      - "8080:80"
    volumes:
      - ./frontend/its-tasty/build:/frontend:ro


  its-tasty-db:
    image: mariadb:latest
    container_name: its-tasty-db
    environment:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MARIADB_DATABASE
    volumes:
      - db-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"


volumes:
  db-data: