version: '3.3'
services:
  its-tasty-backend:
    image: "its-tasty:latest"
    container_name: its-tasty-backend
    environment:
      - OIDC_SECRET
      - OIDC_CALLBACK_URL
      - OIDC_PROVIDER_URL
      - OIDC_ID
      - VACATION_SERVER_URL
      - PUBLIC_HOLIDAY_REGION
      - BOT_API_TOKEN
      - DB_URL
      - DB_NAME
      - DB_USER
      - DB_PW
      - URL_AFTER_LOGIN
      - URL_AFTER_LOGOUT
      - DEV_MODE
      - DEV_CORS
    ports:
      - "8000:80"
    volumes:
      #data is only picked up in dev mode
      - ./testdata/selfSignedTLS:/selfSignedTLS:ro

  its-tasty-db:
    image: postgres:latest
    container_name: its-tasty-db
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  db-data:
