// Package userAPI provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.1-0.20220812203637-fec990c8f823 DO NOT EDIT.
package userAPI

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /dishes/{dishID})
	GetDishesDishID(w http.ResponseWriter, r *http.Request, dishID int64)

	// (POST /dishes/{dishID})
	PostDishesDishID(w http.ResponseWriter, r *http.Request, dishID int64)

	// (GET /getAllDishes)
	GetGetAllDishes(w http.ResponseWriter, r *http.Request)

	// (POST /searchDish)
	PostSearchDish(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDishesDishID operation middleware
func (siw *ServerInterfaceWrapper) GetDishesDishID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "dishID" -------------
	var dishID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "dishID", runtime.ParamLocationPath, chi.URLParam(r, "dishID"), &dishID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dishID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDishesDishID(w, r, dishID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostDishesDishID operation middleware
func (siw *ServerInterfaceWrapper) PostDishesDishID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "dishID" -------------
	var dishID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "dishID", runtime.ParamLocationPath, chi.URLParam(r, "dishID"), &dishID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dishID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDishesDishID(w, r, dishID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetGetAllDishes operation middleware
func (siw *ServerInterfaceWrapper) GetGetAllDishes(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGetAllDishes(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostSearchDish operation middleware
func (siw *ServerInterfaceWrapper) PostSearchDish(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSearchDish(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dishes/{dishID}", wrapper.GetDishesDishID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dishes/{dishID}", wrapper.PostDishesDishID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/getAllDishes", wrapper.GetGetAllDishes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/searchDish", wrapper.PostSearchDish)
	})

	return r
}

type GetDishesDishIDRequestObject struct {
	DishID int64 `json:"dishID"`
}

type GetDishesDishID200JSONResponse GetDishResp

func (t GetDishesDishID200JSONResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal((GetDishResp)(t))
}

type GetDishesDishID400JSONResponse BasicError

func (t GetDishesDishID400JSONResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal((BasicError)(t))
}

type GetDishesDishID401Response struct {
}

type GetDishesDishID404Response struct {
}

type GetDishesDishID500JSONResponse BasicError

func (t GetDishesDishID500JSONResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal((BasicError)(t))
}

type PostDishesDishIDRequestObject struct {
	DishID int64 `json:"dishID"`
	Body   *PostDishesDishIDJSONRequestBody
}

type PostDishesDishID200Response struct {
}

type PostDishesDishID400JSONResponse BasicError

func (t PostDishesDishID400JSONResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal((BasicError)(t))
}

type PostDishesDishID401Response struct {
}

type PostDishesDishID404Response struct {
}

type PostDishesDishID500JSONResponse BasicError

func (t PostDishesDishID500JSONResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal((BasicError)(t))
}

type GetGetAllDishesRequestObject struct {
}

type GetGetAllDishes200JSONResponse GetAllDishesResponse

func (t GetGetAllDishes200JSONResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal((GetAllDishesResponse)(t))
}

type GetGetAllDishes401Response struct {
}

type GetGetAllDishes500JSONResponse BasicError

func (t GetGetAllDishes500JSONResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal((BasicError)(t))
}

type PostSearchDishRequestObject struct {
	Body *PostSearchDishJSONRequestBody
}

type PostSearchDish200JSONResponse SearchDishResp

func (t PostSearchDish200JSONResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal((SearchDishResp)(t))
}

type PostSearchDish401Response struct {
}

type PostSearchDish500JSONResponse BasicError

func (t PostSearchDish500JSONResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal((BasicError)(t))
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /dishes/{dishID})
	GetDishesDishID(ctx context.Context, request GetDishesDishIDRequestObject) interface{}

	// (POST /dishes/{dishID})
	PostDishesDishID(ctx context.Context, request PostDishesDishIDRequestObject) interface{}

	// (GET /getAllDishes)
	GetGetAllDishes(ctx context.Context, request GetGetAllDishesRequestObject) interface{}

	// (POST /searchDish)
	PostSearchDish(ctx context.Context, request PostSearchDishRequestObject) interface{}
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, args interface{}) interface{}

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDishesDishID operation middleware
func (sh *strictHandler) GetDishesDishID(w http.ResponseWriter, r *http.Request, dishID int64) {
	var request GetDishesDishIDRequestObject

	request.DishID = dishID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) interface{} {
		return sh.ssi.GetDishesDishID(ctx, request.(GetDishesDishIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDishesDishID")
	}

	response := handler(r.Context(), w, r, request)

	switch v := response.(type) {
	case GetDishesDishID200JSONResponse:
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		writeJSON(w, v)
	case GetDishesDishID400JSONResponse:
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(400)
		writeJSON(w, v)
	case GetDishesDishID401Response:
		w.WriteHeader(401)
	case GetDishesDishID404Response:
		w.WriteHeader(404)
	case GetDishesDishID500JSONResponse:
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(500)
		writeJSON(w, v)
	case error:
		sh.options.ResponseErrorHandlerFunc(w, r, v)
	case nil:
	default:
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", v))
	}
}

// PostDishesDishID operation middleware
func (sh *strictHandler) PostDishesDishID(w http.ResponseWriter, r *http.Request, dishID int64) {
	var request PostDishesDishIDRequestObject

	request.DishID = dishID

	var body PostDishesDishIDJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) interface{} {
		return sh.ssi.PostDishesDishID(ctx, request.(PostDishesDishIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostDishesDishID")
	}

	response := handler(r.Context(), w, r, request)

	switch v := response.(type) {
	case PostDishesDishID200Response:
		w.WriteHeader(200)
	case PostDishesDishID400JSONResponse:
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(400)
		writeJSON(w, v)
	case PostDishesDishID401Response:
		w.WriteHeader(401)
	case PostDishesDishID404Response:
		w.WriteHeader(404)
	case PostDishesDishID500JSONResponse:
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(500)
		writeJSON(w, v)
	case error:
		sh.options.ResponseErrorHandlerFunc(w, r, v)
	case nil:
	default:
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", v))
	}
}

// GetGetAllDishes operation middleware
func (sh *strictHandler) GetGetAllDishes(w http.ResponseWriter, r *http.Request) {
	var request GetGetAllDishesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) interface{} {
		return sh.ssi.GetGetAllDishes(ctx, request.(GetGetAllDishesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGetAllDishes")
	}

	response := handler(r.Context(), w, r, request)

	switch v := response.(type) {
	case GetGetAllDishes200JSONResponse:
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		writeJSON(w, v)
	case GetGetAllDishes401Response:
		w.WriteHeader(401)
	case GetGetAllDishes500JSONResponse:
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(500)
		writeJSON(w, v)
	case error:
		sh.options.ResponseErrorHandlerFunc(w, r, v)
	case nil:
	default:
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", v))
	}
}

// PostSearchDish operation middleware
func (sh *strictHandler) PostSearchDish(w http.ResponseWriter, r *http.Request) {
	var request PostSearchDishRequestObject

	var body PostSearchDishJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) interface{} {
		return sh.ssi.PostSearchDish(ctx, request.(PostSearchDishRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostSearchDish")
	}

	response := handler(r.Context(), w, r, request)

	switch v := response.(type) {
	case PostSearchDish200JSONResponse:
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(200)
		writeJSON(w, v)
	case PostSearchDish401Response:
		w.WriteHeader(401)
	case PostSearchDish500JSONResponse:
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(500)
		writeJSON(w, v)
	case error:
		sh.options.ResponseErrorHandlerFunc(w, r, v)
	case nil:
	default:
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", v))
	}
}

func writeJSON(w http.ResponseWriter, v interface{}) {
	if err := json.NewEncoder(w).Encode(v); err != nil {
		fmt.Fprintln(w, err)
	}
}

func writeRaw(w http.ResponseWriter, b []byte) {
	if _, err := w.Write(b); err != nil {
		fmt.Fprintln(w, err)
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYT2/bxhP9KoP9/Q4tQEhy4hSBbk5UpEKbxLDTU+DDihyJm5C7zM5QgmrwuxezS0mk",
	"SSEu4DQterLC/TNvZt68mc29Sl1ZOYuWSc3vFaU5ljr8fKXJpD9777z8q/KuQs8Gw9ou1yx/eV+hmiti",
	"b+xGNU1y+OJWnzBl1STqDfJVUSwM5Ug3SJWzhHI0Q0q9qdg4q+bqynu9h53hHHRRwGfrdhYyQzksF6QS",
	"ZRhLGh6THcuFStTa+VIgKWP5p0t1xGEs4wa9OiHTYqkFJqgE0/DiBbI2BWbQ+QxuDTqAUsmDeOjt5kaz",
	"xGDo2Ra93iD4sA5r54FzQ+GeCbwvDTNmYNbAOXoE7RGsg61jJNgjn1yxdbmKnlhdjoTwnS5RIHKOB5AP",
	"0pMol6a192hTfO1qyyNoS/kerjEl0gkqtEez0dhG596vfyf0w0tvRlw/IPX4pUYK6zWhfxiR8BFyTWAd",
	"Swwxk6hMVKLQ1qWaf7xIniXPk8vkxd15YDFHWWYEkC6ue7kbHhpDTw8z9yvuCUrUts1sAltd1Nj7RpHR",
	"nGsGfYwssfY0geUaSudRVi38gf6QdGFA5ZHQMhx5BWuDRQaps6yNpRAa3WPWRI0Un8cULb8/Zn2khN46",
	"Yoj74EQP6jJpAm/NJueQghZBWNvlrkDIDbHz+/NFGmsT9vv9flKWkyzr1mumGceY2q/W4MqX2gj/5h9j",
	"AQzZPObviQJ3I/G50YxRBL6M0DZSEzhmJhDgTP37Y/E/gpUPnGnPjsG7Re3T/DEAC+c+11ULb7mA1f6Y",
	"PWij1UcsK+9GdUTMyZUUjIvXw/w8cOF42decGJPa111Ot/A7yiAaPBbyVvoH1y0XB+pGB9rzoieGYael",
	"kGubnYTGifDuDOHj2sj5wHUF+GhboDdycW0zicHw2Adf40HtAtIjxpP9lXMFans+8F0LwyTIMWPXbsS4",
	"CNrV9VK6rttRkFuS7IvUgrYZbA3uAjbWItNIQRpc7WGFhdtiBiVaisQL9caGCzG+/HALP/ziKlzXRbH/",
	"ET5o4j1IhxCDKlFb9BRRzCYXk1noTxVaXRk1V88ns8lzSbrmPOR7Gg1M72PiG/m2wZEW9gYZstC+CQrz",
	"GY9aLN50Fa7fj4xNizoTqT20HQIZQtryDNjkt7PLLFqJM83iMIJU2usSGT2p+cd7ZQSLoFeHhn2aVk4p",
	"ZF9j0k5d4spXCdjcyfE4RoW4PJvN5I/oMsaOrquqMGmAOv1EEpP7joX/e1yrufrf9DT4Tdupb9odiQJp",
	"zgxFwiXBKUORXrmaT0NHk6jLJ0TUGUJHAL3SGSxtVTNkmnW0fTFkROCcRcwoSuXG2Lj38txEGVpdrMEm",
	"US/+NoeWltFbXQDKDljVDCb4FzTBWIyHKkc8OmZhd/rrE/ba0fdkbNDyVy7bP1kku7276QujYGzG66Qf",
	"sts6TZHoe7F28R9ibZOo6abzFjyr3zfItW/HgeUidJv+kzB0mYEad9+Z6ttq5PA9OxKU6MbYa/YvJvwf",
	"mEc6jnThvwZG1ej2OD62U6nMpIfBfaBMpyFRfRu16I/Sj9eLJzc+3lp7QvTv5UaTKEK/PXSU/hW/uVQX",
	"wO1rP+5Tiap9oeYqZ67m02khe3JHPH85ezmbyhh2db2cbi9Uc9f8GQAA//8TTEvurRIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
