// Package botAPI provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package botAPI

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostCreateOrUpdateDish request with any body
	PostCreateOrUpdateDishWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCreateOrUpdateDish(ctx context.Context, body PostCreateOrUpdateDishJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDishesDishID request
	GetDishesDishID(ctx context.Context, dishID int64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStatisticsCurrentVotingStreaks request
	GetStatisticsCurrentVotingStreaks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStatisticsLongestVotingStreaks request
	GetStatisticsLongestVotingStreaks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostCreateOrUpdateDishWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCreateOrUpdateDishRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCreateOrUpdateDish(ctx context.Context, body PostCreateOrUpdateDishJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCreateOrUpdateDishRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDishesDishID(ctx context.Context, dishID int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDishesDishIDRequest(c.Server, dishID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStatisticsCurrentVotingStreaks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStatisticsCurrentVotingStreaksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStatisticsLongestVotingStreaks(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStatisticsLongestVotingStreaksRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostCreateOrUpdateDishRequest calls the generic PostCreateOrUpdateDish builder with application/json body
func NewPostCreateOrUpdateDishRequest(server string, body PostCreateOrUpdateDishJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCreateOrUpdateDishRequestWithBody(server, "application/json", bodyReader)
}

// NewPostCreateOrUpdateDishRequestWithBody generates requests for PostCreateOrUpdateDish with any type of body
func NewPostCreateOrUpdateDishRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/createOrUpdateDish")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetDishesDishIDRequest generates requests for GetDishesDishID
func NewGetDishesDishIDRequest(server string, dishID int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "dishID", runtime.ParamLocationPath, dishID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dishes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStatisticsCurrentVotingStreaksRequest generates requests for GetStatisticsCurrentVotingStreaks
func NewGetStatisticsCurrentVotingStreaksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/statistics/currentVotingStreaks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStatisticsLongestVotingStreaksRequest generates requests for GetStatisticsLongestVotingStreaks
func NewGetStatisticsLongestVotingStreaksRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/statistics/longestVotingStreaks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostCreateOrUpdateDish request with any body
	PostCreateOrUpdateDishWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCreateOrUpdateDishResponse, error)

	PostCreateOrUpdateDishWithResponse(ctx context.Context, body PostCreateOrUpdateDishJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCreateOrUpdateDishResponse, error)

	// GetDishesDishID request
	GetDishesDishIDWithResponse(ctx context.Context, dishID int64, reqEditors ...RequestEditorFn) (*GetDishesDishIDResponse, error)

	// GetStatisticsCurrentVotingStreaks request
	GetStatisticsCurrentVotingStreaksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStatisticsCurrentVotingStreaksResponse, error)

	// GetStatisticsLongestVotingStreaks request
	GetStatisticsLongestVotingStreaksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStatisticsLongestVotingStreaksResponse, error)
}

type PostCreateOrUpdateDishResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateOrUpdateDishResp
	JSON500      *BasicError
}

// Status returns HTTPResponse.Status
func (r PostCreateOrUpdateDishResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCreateOrUpdateDishResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDishesDishIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetDishResp
	JSON400      *BasicError
	JSON500      *BasicError
}

// Status returns HTTPResponse.Status
func (r GetDishesDishIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDishesDishIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStatisticsCurrentVotingStreaksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CurrentVotingStreakResp
}

// Status returns HTTPResponse.Status
func (r GetStatisticsCurrentVotingStreaksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStatisticsCurrentVotingStreaksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStatisticsLongestVotingStreaksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LongestVotingStreakResp
}

// Status returns HTTPResponse.Status
func (r GetStatisticsLongestVotingStreaksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStatisticsLongestVotingStreaksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostCreateOrUpdateDishWithBodyWithResponse request with arbitrary body returning *PostCreateOrUpdateDishResponse
func (c *ClientWithResponses) PostCreateOrUpdateDishWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCreateOrUpdateDishResponse, error) {
	rsp, err := c.PostCreateOrUpdateDishWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCreateOrUpdateDishResponse(rsp)
}

func (c *ClientWithResponses) PostCreateOrUpdateDishWithResponse(ctx context.Context, body PostCreateOrUpdateDishJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCreateOrUpdateDishResponse, error) {
	rsp, err := c.PostCreateOrUpdateDish(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCreateOrUpdateDishResponse(rsp)
}

// GetDishesDishIDWithResponse request returning *GetDishesDishIDResponse
func (c *ClientWithResponses) GetDishesDishIDWithResponse(ctx context.Context, dishID int64, reqEditors ...RequestEditorFn) (*GetDishesDishIDResponse, error) {
	rsp, err := c.GetDishesDishID(ctx, dishID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDishesDishIDResponse(rsp)
}

// GetStatisticsCurrentVotingStreaksWithResponse request returning *GetStatisticsCurrentVotingStreaksResponse
func (c *ClientWithResponses) GetStatisticsCurrentVotingStreaksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStatisticsCurrentVotingStreaksResponse, error) {
	rsp, err := c.GetStatisticsCurrentVotingStreaks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStatisticsCurrentVotingStreaksResponse(rsp)
}

// GetStatisticsLongestVotingStreaksWithResponse request returning *GetStatisticsLongestVotingStreaksResponse
func (c *ClientWithResponses) GetStatisticsLongestVotingStreaksWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetStatisticsLongestVotingStreaksResponse, error) {
	rsp, err := c.GetStatisticsLongestVotingStreaks(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStatisticsLongestVotingStreaksResponse(rsp)
}

// ParsePostCreateOrUpdateDishResponse parses an HTTP response from a PostCreateOrUpdateDishWithResponse call
func ParsePostCreateOrUpdateDishResponse(rsp *http.Response) (*PostCreateOrUpdateDishResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCreateOrUpdateDishResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateOrUpdateDishResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest BasicError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetDishesDishIDResponse parses an HTTP response from a GetDishesDishIDWithResponse call
func ParseGetDishesDishIDResponse(rsp *http.Response) (*GetDishesDishIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDishesDishIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetDishResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BasicError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest BasicError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetStatisticsCurrentVotingStreaksResponse parses an HTTP response from a GetStatisticsCurrentVotingStreaksWithResponse call
func ParseGetStatisticsCurrentVotingStreaksResponse(rsp *http.Response) (*GetStatisticsCurrentVotingStreaksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStatisticsCurrentVotingStreaksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CurrentVotingStreakResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetStatisticsLongestVotingStreaksResponse parses an HTTP response from a GetStatisticsLongestVotingStreaksWithResponse call
func ParseGetStatisticsLongestVotingStreaksResponse(rsp *http.Response) (*GetStatisticsLongestVotingStreaksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStatisticsLongestVotingStreaksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LongestVotingStreakResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /createOrUpdateDish)
	PostCreateOrUpdateDish(w http.ResponseWriter, r *http.Request)

	// (GET /dishes/{dishID})
	GetDishesDishID(w http.ResponseWriter, r *http.Request, dishID int64)

	// (GET /statistics/currentVotingStreaks)
	GetStatisticsCurrentVotingStreaks(w http.ResponseWriter, r *http.Request)

	// (GET /statistics/longestVotingStreaks)
	GetStatisticsLongestVotingStreaks(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostCreateOrUpdateDish operation middleware
func (siw *ServerInterfaceWrapper) PostCreateOrUpdateDish(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCreateOrUpdateDish(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDishesDishID operation middleware
func (siw *ServerInterfaceWrapper) GetDishesDishID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "dishID" -------------
	var dishID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "dishID", runtime.ParamLocationPath, chi.URLParam(r, "dishID"), &dishID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dishID", Err: err})
		return
	}

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDishesDishID(w, r, dishID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetStatisticsCurrentVotingStreaks operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsCurrentVotingStreaks(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatisticsCurrentVotingStreaks(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetStatisticsLongestVotingStreaks operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsLongestVotingStreaks(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatisticsLongestVotingStreaks(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/createOrUpdateDish", wrapper.PostCreateOrUpdateDish)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dishes/{dishID}", wrapper.GetDishesDishID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/statistics/currentVotingStreaks", wrapper.GetStatisticsCurrentVotingStreaks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/statistics/longestVotingStreaks", wrapper.GetStatisticsLongestVotingStreaks)
	})

	return r
}

type PostCreateOrUpdateDishRequestObject struct {
	Body *PostCreateOrUpdateDishJSONRequestBody
}

type PostCreateOrUpdateDishResponseObject interface {
	VisitPostCreateOrUpdateDishResponse(w http.ResponseWriter) error
}

type PostCreateOrUpdateDish200JSONResponse CreateOrUpdateDishResp

func (response PostCreateOrUpdateDish200JSONResponse) VisitPostCreateOrUpdateDishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostCreateOrUpdateDish401Response struct {
}

func (response PostCreateOrUpdateDish401Response) VisitPostCreateOrUpdateDishResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostCreateOrUpdateDish500JSONResponse BasicError

func (response PostCreateOrUpdateDish500JSONResponse) VisitPostCreateOrUpdateDishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDishesDishIDRequestObject struct {
	DishID int64 `json:"dishID"`
}

type GetDishesDishIDResponseObject interface {
	VisitGetDishesDishIDResponse(w http.ResponseWriter) error
}

type GetDishesDishID200JSONResponse GetDishResp

func (response GetDishesDishID200JSONResponse) VisitGetDishesDishIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDishesDishID400JSONResponse BasicError

func (response GetDishesDishID400JSONResponse) VisitGetDishesDishIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDishesDishID401Response struct {
}

func (response GetDishesDishID401Response) VisitGetDishesDishIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetDishesDishID404Response struct {
}

func (response GetDishesDishID404Response) VisitGetDishesDishIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetDishesDishID500JSONResponse BasicError

func (response GetDishesDishID500JSONResponse) VisitGetDishesDishIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetStatisticsCurrentVotingStreaksRequestObject struct {
}

type GetStatisticsCurrentVotingStreaksResponseObject interface {
	VisitGetStatisticsCurrentVotingStreaksResponse(w http.ResponseWriter) error
}

type GetStatisticsCurrentVotingStreaks200JSONResponse CurrentVotingStreakResp

func (response GetStatisticsCurrentVotingStreaks200JSONResponse) VisitGetStatisticsCurrentVotingStreaksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetStatisticsCurrentVotingStreaks500Response struct {
}

func (response GetStatisticsCurrentVotingStreaks500Response) VisitGetStatisticsCurrentVotingStreaksResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetStatisticsLongestVotingStreaksRequestObject struct {
}

type GetStatisticsLongestVotingStreaksResponseObject interface {
	VisitGetStatisticsLongestVotingStreaksResponse(w http.ResponseWriter) error
}

type GetStatisticsLongestVotingStreaks200JSONResponse LongestVotingStreakResp

func (response GetStatisticsLongestVotingStreaks200JSONResponse) VisitGetStatisticsLongestVotingStreaksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetStatisticsLongestVotingStreaks500Response struct {
}

func (response GetStatisticsLongestVotingStreaks500Response) VisitGetStatisticsLongestVotingStreaksResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /createOrUpdateDish)
	PostCreateOrUpdateDish(ctx context.Context, request PostCreateOrUpdateDishRequestObject) (PostCreateOrUpdateDishResponseObject, error)

	// (GET /dishes/{dishID})
	GetDishesDishID(ctx context.Context, request GetDishesDishIDRequestObject) (GetDishesDishIDResponseObject, error)

	// (GET /statistics/currentVotingStreaks)
	GetStatisticsCurrentVotingStreaks(ctx context.Context, request GetStatisticsCurrentVotingStreaksRequestObject) (GetStatisticsCurrentVotingStreaksResponseObject, error)

	// (GET /statistics/longestVotingStreaks)
	GetStatisticsLongestVotingStreaks(ctx context.Context, request GetStatisticsLongestVotingStreaksRequestObject) (GetStatisticsLongestVotingStreaksResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostCreateOrUpdateDish operation middleware
func (sh *strictHandler) PostCreateOrUpdateDish(w http.ResponseWriter, r *http.Request) {
	var request PostCreateOrUpdateDishRequestObject

	var body PostCreateOrUpdateDishJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostCreateOrUpdateDish(ctx, request.(PostCreateOrUpdateDishRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostCreateOrUpdateDish")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostCreateOrUpdateDishResponseObject); ok {
		if err := validResponse.VisitPostCreateOrUpdateDishResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetDishesDishID operation middleware
func (sh *strictHandler) GetDishesDishID(w http.ResponseWriter, r *http.Request, dishID int64) {
	var request GetDishesDishIDRequestObject

	request.DishID = dishID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDishesDishID(ctx, request.(GetDishesDishIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDishesDishID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDishesDishIDResponseObject); ok {
		if err := validResponse.VisitGetDishesDishIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetStatisticsCurrentVotingStreaks operation middleware
func (sh *strictHandler) GetStatisticsCurrentVotingStreaks(w http.ResponseWriter, r *http.Request) {
	var request GetStatisticsCurrentVotingStreaksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatisticsCurrentVotingStreaks(ctx, request.(GetStatisticsCurrentVotingStreaksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatisticsCurrentVotingStreaks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatisticsCurrentVotingStreaksResponseObject); ok {
		if err := validResponse.VisitGetStatisticsCurrentVotingStreaksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetStatisticsLongestVotingStreaks operation middleware
func (sh *strictHandler) GetStatisticsLongestVotingStreaks(w http.ResponseWriter, r *http.Request) {
	var request GetStatisticsLongestVotingStreaksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStatisticsLongestVotingStreaks(ctx, request.(GetStatisticsLongestVotingStreaksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStatisticsLongestVotingStreaks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatisticsLongestVotingStreaksResponseObject); ok {
		if err := validResponse.VisitGetStatisticsLongestVotingStreaksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYX3PbxhH/KjvXzjSZYUilcfugN1nypKztWGM5TTO2H5a4JXHW4Q6+XZBBPfzunbsD",
	"SVAATWVadfokCuD+/+3ub/lFFb6qvSMnrC6/KC5KqjB9fI5sihch+BD/q4OvKYih9G5TosS/0takLhVL",
	"MG6lttvJ7olffKJC1HairgOh0Jvwc61R6MZw+ZY+R1lNXARTi/FOXap3AR1XRkCjICx9AG24hCJKx29M",
	"HngQ3/6EFQ01xafglyAlZR3iYUFZE2mYQZM80Wry0P2JYgpr0lcy1PrKF8kR2JQUCKQ0nLUbhiw11Led",
	"qECfGxNIq8v3B5d7dj4+MmNcD12au6UPFZhldmSDvA/SB/jUsOxCBXQaAkkTHBhhmN8M8lmUVNy/prCi",
	"a3TaRDEemrxGB97ZNiZUQkOpUI42yQPiKcyX6fmklyAufWM11MEvcJFFq2hHw8ZICfSbYTFutVfxq292",
	"MtpwbbFNpWyYAiBY4+5jReOjDS2gxhVNYFOaooQCXXzuYElSlOkryVJ80YUEa4MHdVe38+mhbAvvLaGL",
	"Jejy+BNtYvrH0NpQTDzug++n/4zKHZTOqbV7yJ1RHe3Pb0YAcrPrg056tsNDlJjC3yNEJOPZQ4X3BNws",
	"mD435AQKtJaBkA0FNVERa7HplXHy12cHP4wTWlEYoP1BCvdejmZiMo6/0e5oQiAn//ARNHcSCO/H2+OV",
	"dytigSIL2Ba8W/mItHWSBU7CPGyFLPCOsOpbGbFAbiVlzHEnAkJYHasH40BjyyMJm+ws/cwU+pay3q/Z",
	"izW1Ob7JuQBh0QI6ME6btdEN2oT9UX/iC/7FSPkafzsV9JXNChg2pYcS1wR41gW/BJud/3rIE2WEqpHB",
	"86JCY3eRH/t/mN7dAwwB2/Fl9CPJ6Xl6Q4LGxu44PI4mMbXLACa4Xr3FGMFIjtYUcEUQ0vs0JPfzcApv",
	"KiOxCc2yaz4MBM7HlBFDS3KIzTXVIpfGPWrXjWXFFznnBV37xo2stqsqPk9qTEXcG92dqB4FSw4up0Jr",
	"E5WhvT1K0VDo2HLOHz9M0EtqGSpCBx8UCwb+oNIGW6NtqHvTWc87REoUwH0YSSbtosqnXY0O/kVhl+GY",
	"7joQx4bdFxGWhqyGwjtB4zhlFI/K2NsUB0AFKsjJm32KR6D72rNA/h4casH9sk3htVmVAs7LzoO84Epv",
	"CUrD4kN7ujnyaIa2bdtpVU217o/rOEnPN8sTUx+Xac9DKI7l7wCsMzSpm++PXwS0pnBu9ndD9RGzv6/0",
	"d479zsijx/5J/3dW0pR60hH/dZefdmwncBZNMNLexfMkV+qqNi+pvWpyxky0VhLqZCIPS/XP765u59+9",
	"fPHrwSomKbWNSo1b+hEOFuF9dTsHtNZvuGORjhEWXjJPcnEoZLqa5lKmm6klDtgVIzZanL+7g2/+5mta",
	"Nta238I7ZGnhuZdoRE3UmgJnyxfT76cXaWLX5LA26lL9ML2Y/hBBilKmqGfF4DhI15nnkcbNh8SBovrQ",
	"HQRg5E8MH5RFlq6FP6g8XuNWigzUBkLdZnbOcfTFLkljYK7Vpbr1LMM7ReWuJ5bnXreJS3knlJcO1rU1",
	"eZLMPnGmv/ncjJ/+GGipLtUfZod7dNYdo7PxE3J7PGTi2ZEecO0dZ4z8+eLiSZ3gOntxnPa7piiIeQpv",
	"u4vr1J0AyLAha+Pf3SqY36RtuGykCZRwmHh4hMWzi++HNY4dCY5Ic8Sm9SuTToK//Bcj7/0QMBLt3AkF",
	"hxYofgMWjYBxdSMp0KVxFIW2EzXLDTP7kqPcRqsrGkHtjySgExVjsOae9qs+tlp/gR6xhgFCO6pHfLO7",
	"O2oMWJFQYHX5vhsZsbEOA2N/ohzDatJL1Pkz6OMTgrDPX0dqsWewxmU/49bGhW/kwBATkP5X4HiOGuYJ",
	"DRoFp78Xxc8uno3Q9NwlkSstfeP0/yncWVAMiyl4VgxPVj4J/6uHKz7PhiLiqWjErAnyVRDXalr+mf3m",
	"XzRK5MRy9RR+Ibonp7mjzjkXDNqn1C2S8mM2NIW0/Mjp2hsn3S9Gnf0zF15uxh1lTYTom/2BY6IT7bcP",
	"55193IWeb7AU3kDlWNvf7TN/PZb4p9wRJ36bOL0keuD9z3Fmh4z4NM7uiOAcSFNVj2uhaWlcOvZOgGVX",
	"1BFOfKL8w2IPqGxEJu1gChW2e4KyIPBrCrNF8Pfkvg6HV2P5eUI4nLpQngwOPaacVlyfI7//uP24/XcA",
	"AAD//4p4AjLvFwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
