// Package botAPI provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.1-0.20220906181851-9c600dddea33 DO NOT EDIT.
package botAPI

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostCreateOrUpdateDish request with any body
	PostCreateOrUpdateDishWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostCreateOrUpdateDish(ctx context.Context, body PostCreateOrUpdateDishJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDishesDishID request
	GetDishesDishID(ctx context.Context, dishID int64, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostCreateOrUpdateDishWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCreateOrUpdateDishRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostCreateOrUpdateDish(ctx context.Context, body PostCreateOrUpdateDishJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostCreateOrUpdateDishRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDishesDishID(ctx context.Context, dishID int64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDishesDishIDRequest(c.Server, dishID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostCreateOrUpdateDishRequest calls the generic PostCreateOrUpdateDish builder with application/json body
func NewPostCreateOrUpdateDishRequest(server string, body PostCreateOrUpdateDishJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostCreateOrUpdateDishRequestWithBody(server, "application/json", bodyReader)
}

// NewPostCreateOrUpdateDishRequestWithBody generates requests for PostCreateOrUpdateDish with any type of body
func NewPostCreateOrUpdateDishRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/createOrUpdateDish")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetDishesDishIDRequest generates requests for GetDishesDishID
func NewGetDishesDishIDRequest(server string, dishID int64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "dishID", runtime.ParamLocationPath, dishID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dishes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostCreateOrUpdateDish request with any body
	PostCreateOrUpdateDishWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCreateOrUpdateDishResponse, error)

	PostCreateOrUpdateDishWithResponse(ctx context.Context, body PostCreateOrUpdateDishJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCreateOrUpdateDishResponse, error)

	// GetDishesDishID request
	GetDishesDishIDWithResponse(ctx context.Context, dishID int64, reqEditors ...RequestEditorFn) (*GetDishesDishIDResponse, error)
}

type PostCreateOrUpdateDishResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateOrUpdateDishResp
	JSON500      *BasicError
}

// Status returns HTTPResponse.Status
func (r PostCreateOrUpdateDishResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostCreateOrUpdateDishResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDishesDishIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetDishResp
	JSON400      *BasicError
	JSON500      *BasicError
}

// Status returns HTTPResponse.Status
func (r GetDishesDishIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDishesDishIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostCreateOrUpdateDishWithBodyWithResponse request with arbitrary body returning *PostCreateOrUpdateDishResponse
func (c *ClientWithResponses) PostCreateOrUpdateDishWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostCreateOrUpdateDishResponse, error) {
	rsp, err := c.PostCreateOrUpdateDishWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCreateOrUpdateDishResponse(rsp)
}

func (c *ClientWithResponses) PostCreateOrUpdateDishWithResponse(ctx context.Context, body PostCreateOrUpdateDishJSONRequestBody, reqEditors ...RequestEditorFn) (*PostCreateOrUpdateDishResponse, error) {
	rsp, err := c.PostCreateOrUpdateDish(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostCreateOrUpdateDishResponse(rsp)
}

// GetDishesDishIDWithResponse request returning *GetDishesDishIDResponse
func (c *ClientWithResponses) GetDishesDishIDWithResponse(ctx context.Context, dishID int64, reqEditors ...RequestEditorFn) (*GetDishesDishIDResponse, error) {
	rsp, err := c.GetDishesDishID(ctx, dishID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDishesDishIDResponse(rsp)
}

// ParsePostCreateOrUpdateDishResponse parses an HTTP response from a PostCreateOrUpdateDishWithResponse call
func ParsePostCreateOrUpdateDishResponse(rsp *http.Response) (*PostCreateOrUpdateDishResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostCreateOrUpdateDishResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateOrUpdateDishResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest BasicError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetDishesDishIDResponse parses an HTTP response from a GetDishesDishIDWithResponse call
func ParseGetDishesDishIDResponse(rsp *http.Response) (*GetDishesDishIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDishesDishIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetDishResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BasicError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest BasicError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /createOrUpdateDish)
	PostCreateOrUpdateDish(w http.ResponseWriter, r *http.Request)

	// (GET /dishes/{dishID})
	GetDishesDishID(w http.ResponseWriter, r *http.Request, dishID int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostCreateOrUpdateDish operation middleware
func (siw *ServerInterfaceWrapper) PostCreateOrUpdateDish(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCreateOrUpdateDish(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetDishesDishID operation middleware
func (siw *ServerInterfaceWrapper) GetDishesDishID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "dishID" -------------
	var dishID int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "dishID", runtime.ParamLocationPath, chi.URLParam(r, "dishID"), &dishID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "dishID", Err: err})
		return
	}

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{""})

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDishesDishID(w, r, dishID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/createOrUpdateDish", wrapper.PostCreateOrUpdateDish)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dishes/{dishID}", wrapper.GetDishesDishID)
	})

	return r
}

type PostCreateOrUpdateDishRequestObject struct {
	Body *PostCreateOrUpdateDishJSONRequestBody
}

type PostCreateOrUpdateDishResponseObject interface {
	VisitPostCreateOrUpdateDishResponse(w http.ResponseWriter) error
}

type PostCreateOrUpdateDish200JSONResponse CreateOrUpdateDishResp

func (response PostCreateOrUpdateDish200JSONResponse) VisitPostCreateOrUpdateDishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostCreateOrUpdateDish401Response struct {
}

func (response PostCreateOrUpdateDish401Response) VisitPostCreateOrUpdateDishResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostCreateOrUpdateDish500JSONResponse BasicError

func (response PostCreateOrUpdateDish500JSONResponse) VisitPostCreateOrUpdateDishResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDishesDishIDRequestObject struct {
	DishID int64 `json:"dishID"`
}

type GetDishesDishIDResponseObject interface {
	VisitGetDishesDishIDResponse(w http.ResponseWriter) error
}

type GetDishesDishID200JSONResponse GetDishResp

func (response GetDishesDishID200JSONResponse) VisitGetDishesDishIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDishesDishID400JSONResponse BasicError

func (response GetDishesDishID400JSONResponse) VisitGetDishesDishIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDishesDishID401Response struct {
}

func (response GetDishesDishID401Response) VisitGetDishesDishIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetDishesDishID404Response struct {
}

func (response GetDishesDishID404Response) VisitGetDishesDishIDResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetDishesDishID500JSONResponse BasicError

func (response GetDishesDishID500JSONResponse) VisitGetDishesDishIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /createOrUpdateDish)
	PostCreateOrUpdateDish(ctx context.Context, request PostCreateOrUpdateDishRequestObject) (PostCreateOrUpdateDishResponseObject, error)

	// (GET /dishes/{dishID})
	GetDishesDishID(ctx context.Context, request GetDishesDishIDRequestObject) (GetDishesDishIDResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostCreateOrUpdateDish operation middleware
func (sh *strictHandler) PostCreateOrUpdateDish(w http.ResponseWriter, r *http.Request) {
	var request PostCreateOrUpdateDishRequestObject

	var body PostCreateOrUpdateDishJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostCreateOrUpdateDish(ctx, request.(PostCreateOrUpdateDishRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostCreateOrUpdateDish")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostCreateOrUpdateDishResponseObject); ok {
		if err := validResponse.VisitPostCreateOrUpdateDishResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// GetDishesDishID operation middleware
func (sh *strictHandler) GetDishesDishID(w http.ResponseWriter, r *http.Request, dishID int64) {
	var request GetDishesDishIDRequestObject

	request.DishID = dishID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDishesDishID(ctx, request.(GetDishesDishIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDishesDishID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDishesDishIDResponseObject); ok {
		if err := validResponse.VisitGetDishesDishIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX247bNhN+lQH/H2gLKLLTbHvhO28cpG6aZJED0CK7F7Q0sphIpMIZrasGfvdiSNmy",
	"V0qTAt2iV5JJzembbw7+pDJXN86iZVKLT4qyEmsdXi81meyJ987Lr8a7Bj0bDHe7UrM8uWtQLRSxN3ar",
	"9vvkcOI27zFjtU/UY4+a8aV/2+SacWWofIUfRTZHyrxp2DirFuqN15Zqw5Br1lA4D7mhEjKRli+SOx7I",
	"7Qtd41iTnIIrgEuMOtjBBqMmzGEGbfAkV8ld9xNF6G8xX/JY6y8uC47ArkSPwKWhqN0QRKmxvn2iPH5s",
	"jcdcLd4NLp/YuflKxKgZu7S2hfM1mCI6stN0DNJ5eN8SH0IFbXPwyK23YJhgvRrh2Uu+wJ0YnMpPi2JK",
	"g8XdyOAQ+8a5CrWVOAaVB/C+pLY6gvwF1WJ/vZqAZHXIfC89OyAgEin8LKBwzKCDWn9AoHZD+LFFy5Dp",
	"qiJATQa9SpSgKzRXxvKPF4MfxjJu0Y/yewfCo5eTSEwl/iny57O9QtamkkiGYwlWh9BG+dS321eahYYj",
	"Tctb9HqL4MN9qLUjnVN4WRsWwEzRA6U9gnVw6xgJOuQBCNvWG8EhUfarKnGq4lyWtd6jzfCxa+1E4S1r",
	"OQ9qTI10Unm9aD6RmUTF4CIUeW5Ema6uziAaC51bjvjRXYCeYUdQo7ZwrYi1p2sV6utWVy32N7112Bku",
	"gUvNoI9hBJkU1gXULnQSbeEP9AeEBe7GIwkhj0mEwmCVQ+Ysa2MpIKrP0piqCUJ5zNDyyyPENIb3uSOG",
	"+B0MuaDTtKXw3GxLBuv44EG425WuQigNsfOdSpRhrCcsxDKCruu6tK7TPD8tLSnOKVr0B9p73d17Y7ax",
	"Kd+l4hR+A7H+sokHj7PWG+5ey0SNyC8b8wy7ZcuhvxrxvkSdh2YTK0j9+mB5tX7w7Mlvg9M6SKm9KDW2",
	"cBNNVGJeXq1BV5XbRXbUaEnDxnFsdFaYIrAIw2wOBXJWRpyGgNhwJRbXb17Dtz+5Bou2qrrv4I0m7uDS",
	"sRhRibpFT9HyPH2YzkMZN2h1Y9RCPUrn6SNpR5rLEPUsG82zsFA4mshmnH3DjHG+n2Fg+BuCa1Vp4j6v",
	"1yrWnLQqGSGVR513gL8bYpJ6kGIP3FjnaqGuHPF4tKpIBSS+dHkXJqGzjLET6aapTKTX7D3F+RU3JHn7",
	"v8dCLdT/ZsMKNev3p9n01rM/Zx77FsMBNc5S5Mj38/m9OkFN9OIc9tdtliFRCq/6JeFzgx40wQ6rSp6H",
	"/rBehRZZtNx6DDwMg1RocTF/OM7xW0IPFjEn4WbltibM9B/+wchPdteJaNeW0VtdAcoXsGkZjG1aDoEW",
	"xqII7RM1iwUz+xSj3IvVLU6w9iky5GE+E1TmAx77v5TaaVc9GyUjhvbzH2l1WBwa7XWNjJ7U4l3fMqSw",
	"hoZx3DHOaZWcAPXlPebmHkl4utRM5OK41hgb/ZRWrjeu5WFtCET6t8hxqXNYBzbIP5H077L4Yn4xsbvF",
	"KpEBWrjW5v9Fup+MrMC102H17mZ/s/8zAAD//zkwfqErDgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
