// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboilerPSQL

var TableNames = struct {
	DishOccurrences string
	DishRatings     string
	Dishes          string
	Locations       string
	Users           string
}{
	DishOccurrences: "dish_occurrences",
	DishRatings:     "dish_ratings",
	Dishes:          "dishes",
	Locations:       "locations",
	Users:           "users",
}
