name: build-and-test
on:
  workflow_call:
jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          check-latest: true
          cache: true
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
      - name: Vet
        run: go vet ./...
      - name: Install Vulncheck
        run : go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run Vulncheck
        run: govulncheck ./...
