name: main-workflow
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  call-build-and-check:
    uses: ./.github/workflows/build-and-test.yml
  build-on-docker:
    runs-on: ubuntu-latest
    needs: call-build-and-check
    steps:
      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.docker }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./cmd/server/Dockerfile
          #these are just dummy values to prevent build failures due to empty env vars
          build-args: |
            PUBLIC_URL=https://localhost
            REACT_APP_AUTH_API_BASE_URL=https://localhost
            REACT_APP_PUBLIC_URL=https://localhost
            REACT_APP_USER_API_BASE_URL=https://localhost/userAPI/v1

          tags: ghcr.io/its-luca/itstasty:main-ci-test
          cache-from: type=registry,ref=ghcr.io/its-luca/itstasty:buildcache
          cache-to: type=registry,ref=ghcr.io/its-luca/itstasty:buildcache,mode=max
