name: staging-workflow
on:
  push:
    branches:
      - staging
    tags:
      - v*

jobs:
  call-build-and-check:
   uses: ./.github/workflows/build-and-test.yml
  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: call-build-and-check
    environment: staging
    steps:
        - name: Setup up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to github container registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.docker }}

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: ghcr.io/${{ github.repository }}

        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            platforms: linux/amd64,linux/arm64
            push: true
            file: ./cmd/server/Dockerfile
            build-args: |
              PUBLIC_URL=${{ secrets.PUBLIC_URL }}
              REACT_APP_AUTH_API_BASE_URL=${{ secrets.REACT_APP_AUTH_API_BASE_URL }}
              REACT_APP_PUBLIC_URL=${{ secrets.REACT_APP_PUBLIC_URL }}
              REACT_APP_USER_API_BASE_URL=${{ secrets.REACT_APP_USER_API_BASE_URL }}

            tags: ${{ steps.meta.outputs.tags }}
